.flake8
.gitignore
Pipfile
Pipfile.lock

flake8 instalado
O .gitignore tambem foi alterado, pois os arquivos do PyCharm nao estavam sendo excluidos.
.gitignore gerado com https://gitignore.io/

flake8 installed

---

.github/workflows/pythonapp.yml
Pipfile
Pipfile.lock
django_pagarme/tests/test_zero.py

Hello Renzo, I've created the GitHub CI on this branch. Looks good

Adicionar CI #5

---

.github/workflows/pythonapp.yml

Adicionado CI no Pull Request

---

exemplo/base/settings.py
exemplo/django_assertions.py
exemplo/pagamentos/apps.py
exemplo/pagamentos/templates/pagamentos/produto.html
exemplo/pagamentos/tests/test_pagina_pagamento.py
exemplo/pagamentos/urls.py
exemplo/pagamentos/views.py
exemplo/tests/test_zero.py
setup.cfg

Implementado Pagamento (Autorização) Hardcoded

---

.github/workflows/pythonapp.yml
contrib/env-amostra
exemplo/Pipfile
exemplo/Pipfile.lock
exemplo/base/settings.py
exemplo/pagamentos/templates/pagamentos/produto.html
exemplo/pagamentos/tests/test_pagina_pagamento.py
exemplo/pagamentos/views.py

Extraidas configurações do Pagarme via python-decouple

---

exemplo/Pipfile
exemplo/Pipfile.lock
exemplo/pagamentos/templates/pagamentos/produto.html
exemplo/pagamentos/tests/test_captura.py
exemplo/pagamentos/views.py

Implementada captura de pagamento feito via cartão de crédito

---

.github/workflows/pythonapp.yml
exemplo/Pipfile
exemplo/Pipfile.lock
exemplo/base/settings.py

Configurado Codecov

---

django_pagarme/admin.py

Filtragem feita por item vendido e método de pagamento
close #39

Construindo Admin de Pagamento Capturado

---

contrib/env-amostra
django_pagarme/facade.py
django_pagarme/forms.py
exemplo/Pipfile
exemplo/Pipfile.lock
exemplo/base/settings.py
exemplo/base/tests/test_facade.py
exemplo/base/tests/test_home.py
exemplo/base/urls.py
exemplo/base/views.py
exemplo/pagamentos/templates/pagamentos/home.html
exemplo/pagamentos/urls.py
setup.py

Implementada captura de dados de contato

---

django_pagarme/templates/django_pagarme/pagarme_js_form.html
exemplo/pagamentos/tests/test_pagina_pagamento.py
exemplo/pagamentos/views.py

Extracted customer data from logged user

---

django_pagarme/admin.py
django_pagarme/models.py
django_pagarme/templates/django_pagarme/pagarme_js_form.html
django_pagarme/templatetags/django_pagarme.py
django_pagarme/views.py
exemplo/base/settings.py
exemplo/pagamentos/tests/test_dados_usuario.py

Improved Admin and Fixed UserPayment Profile Bug

---

README.md
codecov.yml

Fixed Codev and added badge

---

django_pagarme/admin.py
django_pagarme/facade.py
django_pagarme/views.py
exemplo/pagamentos/tests/test_captura_boleto.py
exemplo/pagamentos/tests/test_captura_credit_card.py
exemplo/pagamentos/tests/test_dados_usuario.py

Related user on captured payments

---

django_pagarme/facade.py
django_pagarme/views.py
exemplo/base/tests/test_facade.py
exemplo/base/views.py

Informing item slug to contact info listener

---

django_pagarme/facade.py
django_pagarme/models.py
django_pagarme/templates/django_pagarme/pagarme_js_form.html
django_pagarme/urls.py
django_pagarme/views.py
exemplo/pagamentos/templates/django_pagarme/pagarme.html
exemplo/pagamentos/templates/django_pagarme/show_boleto_data.html
exemplo/pagamentos/tests/test_captura_boleto.py
exemplo/pagamentos/tests/test_captura_credit_card.py
exemplo/pagamentos/tests/test_dados_usuario.py
exemplo/pagamentos/tests/test_pagina_pagamento.py

created view for capturing payments

---

django_pagarme/templatetags/django_pagarme.py
django_pagarme/urls.py
django_pagarme/views.py
exemplo/pagamentos/tests/test_pagarme_notifications.py

Included slug on notification link

---

django_pagarme/facade.py
django_pagarme/views.py
exemplo/pagamentos/templates/django_pagarme/thanks.html
exemplo/pagamentos/tests/test_thanks.py

Implemented Thanks Page

---

django_pagarme/facade.py
exemplo/base/views.py
exemplo/pagamentos/tests/test_captura_credit_card.py
exemplo/pagamentos/tests/test_pagarme_notifications.py

Implemented listener for payment status changes

---

README.md
contrib/env-amostra
django_pagarme/facade.py
django_pagarme/views.py
exemplo/base/tests/test_facade.py
exemplo/pagamentos/templates/django_pagarme/contact_form.html

Included Django user on contact listener

---

django_pagarme/forms.py

Inserted placeholder on phone number

---

django_pagarme/templates/django_pagarme/pagarme_js_form.html

Fixed checkout not open when user is logged

---

django_pagarme/admin.py
django_pagarme/models.py

Include Checkout and Contact Form links on PagarmeItemConfigAdmin

---

setup.py

Adicionada dependência do python-pagarme no setup

---

django_pagarme/templates/django_pagarme/pagarme_js_form.html
django_pagarme/urls.py
django_pagarme/views.py
exemplo/pagamentos/tests/test_captura_boleto.py
exemplo/pagamentos/tests/test_captura_credit_card.py
exemplo/pagamentos/tests/test_dados_usuario.py

Acrescentanda slug na página de captura

---

django_pagarme/views.py
exemplo/pagamentos/tests/test_user_data_auto_filling.py

Implemented form filled with user's payment profile

---

django_pagarme/models.py
exemplo/base/settings.py
exemplo/pagamentos/tests/test_pagarme_boleto_notifications.py
exemplo/pagamentos/tests/test_pagarme_credit_card_notifications.py

Consertado bug de recebimento de notificação de boleto

---

django_pagarme/facade.py
exemplo/base/views.py

Carregada chave do pagarme no fachada

---

django_pagarme/__init__.py
django_pagarme/apps.py

Lançada versão 0.16
close #124

Alterado configuração default da app

---

django_pagarme/__init__.py
django_pagarme/models.py
exemplo/base/settings.py
exemplo/pagamentos/tests/test_pagarme_notifications.py

Lançada versão 0.17
close #127

Tratada notificação de pagamento recusado

---

django_pagarme/__init__.py
django_pagarme/facade.py
django_pagarme/views.py
exemplo/pagamentos/tests/test_captura_credit_card.py
exemplo/pagamentos/tests/test_dados_usuario.py
exemplo/pagamentos/tests/test_token_redirect.py

Lançada versão 0.21
close #109

Implementado captura indepotente

---

django_pagarme/facade.py
docker-compose.yml
exemplo/Pipfile.lock

close #155
Atualiadas dependências do projeto Django
Removida opção de restart do docker compose

Alterada obtenção de chave primária de usuário para User.pk

---

django_pagarme/__init__.py
setup.py

Feito release da versão 0.26
